name: Happiness and Horseshit
favicon: null
layout_spectrum: 0.5329633797518909
typography_spectrum: 0.363575404509902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.33477511652745306
  lightness: 0.8692174225579947
  saturation: 0.07314478629268706
  rhythmicContrast: 0.869969728635624
purpose: []
